services:
  surreal:
    image: surrealdb/surrealdb:latest
    ports:
      - "8000:8000"
    environment:
      SURREALDB_USER: root
      SURREALDB_PASS: root
    restart: always
    command: start --log trace --auth --user root --pass root
  surql:
    build:
      dockerfile: ./.images/surql.Dockerfile
    environment:
      SURREALDB_USER: root
      SURREALDB_PASS: root
      SURREALDB_ENDPOINT: http://surreal:8000
    volumes:
      - ./surrealdb:/surrealdb

  mysql:
    image: mysql:latest
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
    restart: always
    volumes:
      - ./mysql/init/init.sql:/mysql/init/init.sql

  postgres:
    image: postgres:latest
    build:
      dockerfile: ./.images/pg.Dockerfile
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: test
    restart: always
    volumes:
      - ./postgres/init/init.sql:/postgres/init/init.sql

  rds:
    image: redis:latest
    ports:
      - 6370:6370

  gopher:
    image: golang:1.22.0
    working_dir: /go/src
    volumes:
      - ./go/src:/go/src

  rust:
    image: rust:latest
    platform: linux/arm64
    working_dir: /rust
    volumes:
      - ./rust:/rust

  node:
    image: node:latest
    working_dir: /node
    volumes:
      - ./node:/node

  deno:
    build:
      dockerfile: ./.images/deno.Dockerfile
    working_dir: /deno
    volumes:
      - ./deno:/deno
    ports:
      - 4507:4507
    command: sh -c "cd deno-svelte && deno task build && deno task serve"

  bun:
    build:
      dockerfile: ./.images/bun.Dockerfile
    ports:
      - 3000:3000

  php:
    image: php:latest
    working_dir: /php
    volumes:
      - ./php:/php

  linux:
    image: ubuntu:latest

  k6:
    image: grafana/k6
    volumes:
      - ./k6:/k6

  plantuml:
    image: plantuml/plantuml-server
    ports:
      - 8080:8080

  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - ./observer/prometheus/config.yml:/etc/prometheus/prometheus.yml
      - ./observer/prometheus/data:/prometheus

  grafana:
    image: grafana/grafana-enterprise
    ports:
      - 3011:3000
    volumes:
      - ./observer/grafana/data:/var/lib/grafana

  vector:
    image: timberio/vector:latest-alpine
    ports:
      - 5044:5044 # Expose Vector's log input port
      - 8664:8664 # Expose Vector's internal metrics
      - 8686:8686 # browser
    volumes:
      - ./observer/vector/config.yaml:/etc/vector/vector.yaml
