[package]
name = "dev"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
algo = { path = "../algo" }
tokio = {version = "1.40.0", features = ["full"]}
