services:
  gopher:
    build:
      dockerfile: ./.images/gopher.Dockerfile
    working_dir: /go/src
    volumes:
      - ./src:/go/src

  client:
    build:
      dockerfile: ./.images/client.Dockerfile
    ports:
      - 8081:8080
    environment:
      SERVER_ADDR: http://server:8080

  server:
    build:
      dockerfile: ./.images/server.Dockerfile
    ports:
      - 8082:8080
    environment:
      SERVER_ADDR: localhost:8080
