services:
  gopher:
    build:
      dockerfile: ./.images/gopher.Dockerfile
    working_dir: /go/src
    volumes:
      - ./src:/go/src

  client:
    build:
      dockerfile: ./.images/client.Dockerfile
    container_name: client
    tty: true
    stdin_open: true
    ports:
      - 8081:8080
    environment:
      SERVER_ADDR: server:8080
    depends_on:
      - server

  server:
    build:
      dockerfile: ./.images/server.Dockerfile
    container_name: server
    ports:
      - 8082:8080
    environment:
      SERVER_ADDR: server:8080
