services:
  cluster-1:
    build:
      dockerfile: ./.images/kind/Dockerfile
    privileged: true
    tty: true
    volumes:
      - ./src:/src
  cluster-2:
    build:
      dockerfile: ./.images/kind/Dockerfile
    privileged: true
    tty: true
    volumes:
      - ./src:/src
