// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.4
// source: queue.proto

package grpc

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The request message for the Enqueue service
type EnqueueRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Prompt        string                 `protobuf:"bytes,1,opt,name=prompt,proto3" json:"prompt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnqueueRequest) Reset() {
	*x = EnqueueRequest{}
	mi := &file_queue_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnqueueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnqueueRequest) ProtoMessage() {}

func (x *EnqueueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_queue_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnqueueRequest.ProtoReflect.Descriptor instead.
func (*EnqueueRequest) Descriptor() ([]byte, []int) {
	return file_queue_proto_rawDescGZIP(), []int{0}
}

func (x *EnqueueRequest) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

type EnqueueResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnqueueResponse) Reset() {
	*x = EnqueueResponse{}
	mi := &file_queue_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnqueueResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnqueueResponse) ProtoMessage() {}

func (x *EnqueueResponse) ProtoReflect() protoreflect.Message {
	mi := &file_queue_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnqueueResponse.ProtoReflect.Descriptor instead.
func (*EnqueueResponse) Descriptor() ([]byte, []int) {
	return file_queue_proto_rawDescGZIP(), []int{1}
}

func (x *EnqueueResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type DequeueRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DequeueRequest) Reset() {
	*x = DequeueRequest{}
	mi := &file_queue_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DequeueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DequeueRequest) ProtoMessage() {}

func (x *DequeueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_queue_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DequeueRequest.ProtoReflect.Descriptor instead.
func (*DequeueRequest) Descriptor() ([]byte, []int) {
	return file_queue_proto_rawDescGZIP(), []int{2}
}

// The request message for the Enqueue service
type DequeueResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Prompt        string                 `protobuf:"bytes,1,opt,name=prompt,proto3" json:"prompt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DequeueResponse) Reset() {
	*x = DequeueResponse{}
	mi := &file_queue_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DequeueResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DequeueResponse) ProtoMessage() {}

func (x *DequeueResponse) ProtoReflect() protoreflect.Message {
	mi := &file_queue_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DequeueResponse.ProtoReflect.Descriptor instead.
func (*DequeueResponse) Descriptor() ([]byte, []int) {
	return file_queue_proto_rawDescGZIP(), []int{3}
}

func (x *DequeueResponse) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

// The request message for the QueueStatus service
type QueueStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QueueId       string                 `protobuf:"bytes,1,opt,name=queue_id,json=queueId,proto3" json:"queue_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueueStatusRequest) Reset() {
	*x = QueueStatusRequest{}
	mi := &file_queue_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueueStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueueStatusRequest) ProtoMessage() {}

func (x *QueueStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_queue_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueueStatusRequest.ProtoReflect.Descriptor instead.
func (*QueueStatusRequest) Descriptor() ([]byte, []int) {
	return file_queue_proto_rawDescGZIP(), []int{4}
}

func (x *QueueStatusRequest) GetQueueId() string {
	if x != nil {
		return x.QueueId
	}
	return ""
}

type QueueStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueueStatusResponse) Reset() {
	*x = QueueStatusResponse{}
	mi := &file_queue_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueueStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueueStatusResponse) ProtoMessage() {}

func (x *QueueStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_queue_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueueStatusResponse.ProtoReflect.Descriptor instead.
func (*QueueStatusResponse) Descriptor() ([]byte, []int) {
	return file_queue_proto_rawDescGZIP(), []int{5}
}

func (x *QueueStatusResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_queue_proto protoreflect.FileDescriptor

const file_queue_proto_rawDesc = "" +
	"\n" +
	"\vqueue.proto\x12\x05Queue\"(\n" +
	"\x0eEnqueueRequest\x12\x16\n" +
	"\x06prompt\x18\x01 \x01(\tR\x06prompt\"+\n" +
	"\x0fEnqueueResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"\x10\n" +
	"\x0eDequeueRequest\")\n" +
	"\x0fDequeueResponse\x12\x16\n" +
	"\x06prompt\x18\x01 \x01(\tR\x06prompt\"/\n" +
	"\x12QueueStatusRequest\x12\x19\n" +
	"\bqueue_id\x18\x01 \x01(\tR\aqueueId\"-\n" +
	"\x13QueueStatusResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status2J\n" +
	"\x0eEnqueueService\x128\n" +
	"\aEnqueue\x12\x15.Queue.EnqueueRequest\x1a\x16.Queue.EnqueueResponse2J\n" +
	"\x0eDequeueService\x128\n" +
	"\aDequeue\x12\x15.Queue.DequeueRequest\x1a\x16.Queue.DequeueResponse2]\n" +
	"\x12QueueStatusService\x12G\n" +
	"\x0eGetQueueStatus\x12\x19.Queue.QueueStatusRequest\x1a\x1a.Queue.QueueStatusResponseB\x0fZ\r./driver/grpcb\x06proto3"

var (
	file_queue_proto_rawDescOnce sync.Once
	file_queue_proto_rawDescData []byte
)

func file_queue_proto_rawDescGZIP() []byte {
	file_queue_proto_rawDescOnce.Do(func() {
		file_queue_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_queue_proto_rawDesc), len(file_queue_proto_rawDesc)))
	})
	return file_queue_proto_rawDescData
}

var file_queue_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_queue_proto_goTypes = []any{
	(*EnqueueRequest)(nil),      // 0: Queue.EnqueueRequest
	(*EnqueueResponse)(nil),     // 1: Queue.EnqueueResponse
	(*DequeueRequest)(nil),      // 2: Queue.DequeueRequest
	(*DequeueResponse)(nil),     // 3: Queue.DequeueResponse
	(*QueueStatusRequest)(nil),  // 4: Queue.QueueStatusRequest
	(*QueueStatusResponse)(nil), // 5: Queue.QueueStatusResponse
}
var file_queue_proto_depIdxs = []int32{
	0, // 0: Queue.EnqueueService.Enqueue:input_type -> Queue.EnqueueRequest
	2, // 1: Queue.DequeueService.Dequeue:input_type -> Queue.DequeueRequest
	4, // 2: Queue.QueueStatusService.GetQueueStatus:input_type -> Queue.QueueStatusRequest
	1, // 3: Queue.EnqueueService.Enqueue:output_type -> Queue.EnqueueResponse
	3, // 4: Queue.DequeueService.Dequeue:output_type -> Queue.DequeueResponse
	5, // 5: Queue.QueueStatusService.GetQueueStatus:output_type -> Queue.QueueStatusResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_queue_proto_init() }
func file_queue_proto_init() {
	if File_queue_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_queue_proto_rawDesc), len(file_queue_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   3,
		},
		GoTypes:           file_queue_proto_goTypes,
		DependencyIndexes: file_queue_proto_depIdxs,
		MessageInfos:      file_queue_proto_msgTypes,
	}.Build()
	File_queue_proto = out.File
	file_queue_proto_goTypes = nil
	file_queue_proto_depIdxs = nil
}
