services:
  gopher:
    build:
      dockerfile: ./.images/gopher.Dockerfile
    working_dir: /go/src
    volumes:
      - ./src:/go/src

  queue:
    build:
      dockerfile: ./.images/queue.Dockerfile
    ports:
      - "8080:8080"
    environment:
      QUEUE_HOST: "queue:8080"

  claude-master:
    build:
      dockerfile: ./.images/master.Dockerfile
    environment:
      WORKER_NUM: 5
      QUEUE_HOST: "queue:8080"
    depends_on:
      - queue
    volumes:
      - ./prompt/tasks:/prompt/tasks

  claude-worker:
    build:
      dockerfile: ./.images/worker.Dockerfile
    environment:
      WORKER_ID: 1
      QUEUE_HOST: "queue:8080"
    depends_on:
      - queue
      - claude-master
    volumes:
      - ./prompt:/prompt/worker_tasks
